### ISSUE TITLE
Config camera.offset parameter doesn't function

### ISSUE THREAD

**Issue by vpatil33** [quantumbagel/DroneTracker#1]
I'm trying to put a 45 degree offset on the camera movement, however when editing the camera.offset parameter in config.yml, I don't see any change in how the camera is pointed. There is no difference in the pan of the camera between an offset of 0 and 45 (assuming the drone position is constant).

From what I understand, the camera.offset parameter is for offsetting the pan (tell me if this is wrong) of the camera. My specific problem is that when a drone is directly south of the camera, the camera is instead pointing southeast. So, I am trying to enforce a 45 degree offset to correct this. For the record, I don't think this is an issue with the camera incorrectly calculating the pan as the pan printing in the console when running with debug output seems correct. I think that it's just that the camera is not mounted facing north, hence the offset is needed.

Here is a screenshot of the relevant portion of my config file:
![image](https://github.com/quantumbagel/CameraDistance/assets/66751699/60f8a4a3-77af-44ee-8c81-ab52475424f0)

**Comment by quantumbagel** [comment]
Fixed by #2
